# Generated by Django 2.2 on 2021-06-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_app', '0002_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
